'''
Game rules
1. A game co-ordinator inputs the number of players to a game
2. At the start of the game, all players are asked for their names
3. At the start of each round, a new magic number between 1 and 10 (not visible to the players) is generated
4. Each player is asked for their guess
5. The player(s) with the closest guesses win 1 point
6. The user then has a choice to continue to the next round or stop the game
7. At the end of the game, the total points scored by each player is listed and the winner(s) is announced.
'''

import random
from collections import Counter

class game():
   
    def __init__(self,count):
        "Initiating the variable and system generated number"
        self.total_players = count
        self.magic_num = random.randint(1,10)
        #print("\n Random number generated by computer: ",self.magic_num,"\n")
        self.player_list = []
        self.final_winner = []
        
    def start_game(self):
        "Starting the game"
        self.player_name()
        
    def player_name(self):
        "Getting a names of players and appending it to the list"
        for self.each_player in range(self.total_players):
            self.name = input(f"Enter player{self.each_player+1} name: ") 
            self.player_list.append(self.name)
        self.play_game()
        
    def play_game(self):
        "Asking to choose a number a checking the refference between choosen and random number"
        self.player_diff_num_list = []
        for self.each_player in range(self.total_players):
            self.gussed_number = int(input(f"Player{self.each_player+1}, Choose a number between 1 to 10: "))
            self.diff = abs(self.gussed_number - self.magic_num)
            self.player_diff_num_list.append(self.diff)
        self.winner()

    def winner(self):
        "Calculatin the winner of one game"
        self.win = min(self.player_diff_num_list)
        self.index_player_list = self.player_diff_num_list.index(self.win) 
        self.winner_name = self.player_list[self.index_player_list]
        print("winner is : ",self.winner_name)
        self.final_winner.append(self.winner_name)
        self.play_again()
    
    def play_again(self):
        "Asking if they want to play again"
        opt = input("\n wanna guess again? (Y/N): ")
        if opt == 'Y':
            self.play_game()
        elif opt == 'N':
            print("\n GAME OVER")
            self.game_winner()
            
    def game_winner(self):
        "Displaying the times eash player has won and printing the final winner"
        self.player_diff_num_list = []
        for self.each_player in range(self.total_players):
            win_times = self.final_winner.count(self.player_list[self.each_player])
            print(f"{self.player_list[self.each_player]} won {win_times} times")
            self.player_diff_num_list.append(win_times)
        self.win = max(self.player_diff_num_list)
        self.index_player_list = self.player_diff_num_list.index(self.win) 
        self.winner_name = self.player_list[self.index_player_list]
        print("\n \t \t FINAL GAME WINNER IS: ",self.winner_name,"\n")
            

if __name__ == "__main__":

    no_of_players = int(input("\nHow many players?: "))
    g = game(no_of_players)
    g.start_game()

   
       





    